from apps.phonebook.serializers.email import EmailNestedSerializer, EmailSerializer
from apps.phonebook.serializers.phone_number import PhoneNumberNestedSerializer, PhoneNumberSerializer
from apps.phonebook.serializers.phonebook import PhonebookSerializer
