# Generated by Django 3.2.7 on 2022-06-26 22:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('switchboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('phonebook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=100)),
                ('note', models.CharField(max_length=200)),
                ('consultant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('switchboard_phone_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='switchboard.switchboard')),
                ('user_phone_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='phonebook.phonenumber')),
            ],
        ),
    ]
